SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS IN ("DONE")
GROUP BY A.WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES