
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT 
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY HAVING CATEGORY IN ('과자','국','김치','식용유')
    )
ORDER BY PRICE DESC


-- 식품분류별 가격이 제일 비싼 식품의 분류, 가격, 이름--
-- 카테고리 과자 국 김치 식용유 --
-- 식품 가격 기준 내림차순--